---
triple:          'arm64-apple-darwin'
binary-path:     '/Users/benjamingayda-knop/Audsbildung Fachinformatiker /Dienstag:06.05.2025/Produktinformation.1/Produktinformation'
relocations:     []
...
